package br.com.sistemaoptica.entity;

public enum StatusPedido {
    RECEBIDO,
    AGUARDANDO_APROVACAO,
    AGUARDANDO_PAGAMENTO,
    DIGITADO,
    IMPRESSO,
    ESTOQUE,
    SEPARACAO,
    SURFACAGEM_F5,
    SURFACAGEM_FREEFORM,
    ANTI_RISCO_SPIN,
    COLORACAO,
    ANTI_RISCO,
    TRATAMENTO,
    CORTE,
    GRAVACAO,
    MONTAGEM,
    CONTROLE_QUALIDADE,
    DISTRIBUICAO,
    FINANCEIRO,
    PRONTO,
    ENTREGUE,
    RETRABALHO,
    CANCELADO
}
